# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SweeperSettingsTab = QtWidgets.QWidget(self.centralwidget)
        self.SweeperSettingsTab.setEnabled(True)
        self.SweeperSettingsTab.setMinimumSize(QtCore.QSize(300, 200))
        self.SweeperSettingsTab.setMaximumSize(QtCore.QSize(600, 400))
        self.SweeperSettingsTab.setObjectName("SweeperSettingsTab")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(90, 300, 386, 41))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Confirm = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.Confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Confirm.setObjectName("Confirm")
        self.horizontalLayout_2.addWidget(self.Confirm)
        self.Start = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Start.setObjectName("Start")
        self.horizontalLayout_2.addWidget(self.Start)
        self.Cancel = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.deviceName = QtWidgets.QLineEdit(self.SweeperSettingsTab)
        self.deviceName.setGeometry(QtCore.QRect(120, 80, 241, 21))
        self.deviceName.setObjectName("deviceName")
        self.advancedSettings = QtWidgets.QToolButton(self.SweeperSettingsTab)
        self.advancedSettings.setGeometry(QtCore.QRect(530, 10, 31, 22))
        self.advancedSettings.setObjectName("advancedSettings")
        self.label_2 = QtWidgets.QLabel(self.SweeperSettingsTab)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 79, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DeviceNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.DeviceNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DeviceNameLabel.setObjectName("DeviceNameLabel")
        self.gridLayout_2.addWidget(self.DeviceNameLabel, 0, 0, 1, 1)
        self.TDAFLabel1 = QtWidgets.QLabel(self.layoutWidget)
        self.TDAFLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel1.setObjectName("TDAFLabel1")
        self.gridLayout_2.addWidget(self.TDAFLabel1, 1, 0, 1, 1)
        self.TDAFLabel4 = QtWidgets.QLabel(self.layoutWidget)
        self.TDAFLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel4.setObjectName("TDAFLabel4")
        self.gridLayout_2.addWidget(self.TDAFLabel4, 2, 0, 1, 1)
        self.TDAFLabel7 = QtWidgets.QLabel(self.layoutWidget)
        self.TDAFLabel7.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel7.setObjectName("TDAFLabel7")
        self.gridLayout_2.addWidget(self.TDAFLabel7, 3, 0, 1, 1)
        self.TDAFLabel10 = QtWidgets.QLabel(self.layoutWidget)
        self.TDAFLabel10.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel10.setObjectName("TDAFLabel10")
        self.gridLayout_2.addWidget(self.TDAFLabel10, 4, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 110, 53, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TDAFLabel2 = QtWidgets.QLabel(self.layoutWidget1)
        self.TDAFLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel2.setObjectName("TDAFLabel2")
        self.gridLayout_3.addWidget(self.TDAFLabel2, 0, 0, 1, 1)
        self.TDAFLabel5 = QtWidgets.QLabel(self.layoutWidget1)
        self.TDAFLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel5.setObjectName("TDAFLabel5")
        self.gridLayout_3.addWidget(self.TDAFLabel5, 1, 0, 1, 1)
        self.TDAFLabel8 = QtWidgets.QLabel(self.layoutWidget1)
        self.TDAFLabel8.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel8.setObjectName("TDAFLabel8")
        self.gridLayout_3.addWidget(self.TDAFLabel8, 2, 0, 1, 1)
        self.TDAFLabel11 = QtWidgets.QLabel(self.layoutWidget1)
        self.TDAFLabel11.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel11.setObjectName("TDAFLabel11")
        self.gridLayout_3.addWidget(self.TDAFLabel11, 3, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(380, 70, 84, 201))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TDAFLabel13 = QtWidgets.QLabel(self.layoutWidget2)
        self.TDAFLabel13.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel13.setObjectName("TDAFLabel13")
        self.gridLayout_5.addWidget(self.TDAFLabel13, 0, 0, 1, 1)
        self.TDAFLabel3 = QtWidgets.QLabel(self.layoutWidget2)
        self.TDAFLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel3.setObjectName("TDAFLabel3")
        self.gridLayout_5.addWidget(self.TDAFLabel3, 1, 0, 1, 1)
        self.TDAFLabel6 = QtWidgets.QLabel(self.layoutWidget2)
        self.TDAFLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel6.setObjectName("TDAFLabel6")
        self.gridLayout_5.addWidget(self.TDAFLabel6, 2, 0, 1, 1)
        self.TDAFLabel9 = QtWidgets.QLabel(self.layoutWidget2)
        self.TDAFLabel9.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel9.setObjectName("TDAFLabel9")
        self.gridLayout_5.addWidget(self.TDAFLabel9, 3, 0, 1, 1)
        self.TDAFLabel12 = QtWidgets.QLabel(self.layoutWidget2)
        self.TDAFLabel12.setAlignment(QtCore.Qt.AlignCenter)
        self.TDAFLabel12.setObjectName("TDAFLabel12")
        self.gridLayout_5.addWidget(self.TDAFLabel12, 4, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(280, 110, 81, 161))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tempStopValue = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.tempStopValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tempStopValue.setAlignment(QtCore.Qt.AlignCenter)
        self.tempStopValue.setProperty("showGroupSeparator", False)
        self.tempStopValue.setObjectName("tempStopValue")
        self.gridLayout_4.addWidget(self.tempStopValue, 0, 0, 1, 1)
        self.dcStopValue = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.dcStopValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dcStopValue.setAlignment(QtCore.Qt.AlignCenter)
        self.dcStopValue.setObjectName("dcStopValue")
        self.gridLayout_4.addWidget(self.dcStopValue, 1, 0, 1, 1)
        self.acStopValue = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.acStopValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.acStopValue.setAlignment(QtCore.Qt.AlignCenter)
        self.acStopValue.setObjectName("acStopValue")
        self.gridLayout_4.addWidget(self.acStopValue, 2, 0, 1, 1)
        self.fStopValue = QtWidgets.QSpinBox(self.layoutWidget3)
        self.fStopValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fStopValue.setAlignment(QtCore.Qt.AlignCenter)
        self.fStopValue.setObjectName("fStopValue")
        self.gridLayout_4.addWidget(self.fStopValue, 3, 0, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(470, 70, 81, 201))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tempCurrentDisplay = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.tempCurrentDisplay.setEnabled(True)
        self.tempCurrentDisplay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tempCurrentDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.tempCurrentDisplay.setReadOnly(True)
        self.tempCurrentDisplay.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tempCurrentDisplay.setObjectName("tempCurrentDisplay")
        self.gridLayout_6.addWidget(self.tempCurrentDisplay, 0, 0, 1, 1)
        self.tempStepValue = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.tempStepValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tempStepValue.setAlignment(QtCore.Qt.AlignCenter)
        self.tempStepValue.setObjectName("tempStepValue")
        self.gridLayout_6.addWidget(self.tempStepValue, 1, 0, 1, 1)
        self.dcStepValue = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.dcStepValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dcStepValue.setAlignment(QtCore.Qt.AlignCenter)
        self.dcStepValue.setObjectName("dcStepValue")
        self.gridLayout_6.addWidget(self.dcStepValue, 2, 0, 1, 1)
        self.acStepValue = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.acStepValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.acStepValue.setAlignment(QtCore.Qt.AlignCenter)
        self.acStepValue.setObjectName("acStepValue")
        self.gridLayout_6.addWidget(self.acStepValue, 3, 0, 1, 1)
        self.fSampleCountValue = QtWidgets.QSpinBox(self.layoutWidget4)
        self.fSampleCountValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fSampleCountValue.setAlignment(QtCore.Qt.AlignCenter)
        self.fSampleCountValue.setObjectName("fSampleCountValue")
        self.gridLayout_6.addWidget(self.fSampleCountValue, 4, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.SweeperSettingsTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(120, 110, 81, 161))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tempStartValue = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.tempStartValue.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tempStartValue.setFont(font)
        self.tempStartValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tempStartValue.setMouseTracking(False)
        self.tempStartValue.setAccessibleName("")
        self.tempStartValue.setAutoFillBackground(False)
        self.tempStartValue.setStyleSheet("")
        self.tempStartValue.setWrapping(False)
        self.tempStartValue.setFrame(True)
        self.tempStartValue.setAlignment(QtCore.Qt.AlignCenter)
        self.tempStartValue.setProperty("showGroupSeparator", False)
        self.tempStartValue.setObjectName("tempStartValue")
        self.gridLayout.addWidget(self.tempStartValue, 0, 0, 1, 1)
        self.dcStartValue = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.dcStartValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dcStartValue.setAlignment(QtCore.Qt.AlignCenter)
        self.dcStartValue.setObjectName("dcStartValue")
        self.gridLayout.addWidget(self.dcStartValue, 1, 0, 1, 1)
        self.acStartValue = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.acStartValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.acStartValue.setAlignment(QtCore.Qt.AlignCenter)
        self.acStartValue.setObjectName("acStartValue")
        self.gridLayout.addWidget(self.acStartValue, 2, 0, 1, 1)
        self.fStartValue = QtWidgets.QSpinBox(self.layoutWidget5)
        self.fStartValue.setMinimumSize(QtCore.QSize(0, 0))
        self.fStartValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fStartValue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fStartValue.setAlignment(QtCore.Qt.AlignCenter)
        self.fStartValue.setReadOnly(False)
        self.fStartValue.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.fStartValue.setObjectName("fStartValue")
        self.gridLayout.addWidget(self.fStartValue, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.SweeperSettingsTab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuZurich_Instruments_Control_Panel = QtWidgets.QMenu(self.menubar)
        self.menuZurich_Instruments_Control_Panel.setObjectName("menuZurich_Instruments_Control_Panel")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_PyZurich = QtWidgets.QAction(MainWindow)
        self.actionAbout_PyZurich.setObjectName("actionAbout_PyZurich")
        self.menuZurich_Instruments_Control_Panel.addAction(self.actionAbout_PyZurich)
        self.menubar.addAction(self.menuZurich_Instruments_Control_Panel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Confirm.setText(_translate("MainWindow", "Confirm"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.advancedSettings.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Temperaure / DC / AC / Frequency Sweep Mode"))
        self.DeviceNameLabel.setText(_translate("MainWindow", "DeviceName"))
        self.TDAFLabel1.setText(_translate("MainWindow", "T Start"))
        self.TDAFLabel4.setText(_translate("MainWindow", "DC Start"))
        self.TDAFLabel7.setText(_translate("MainWindow", "AC Start"))
        self.TDAFLabel10.setText(_translate("MainWindow", "F Start"))
        self.TDAFLabel2.setText(_translate("MainWindow", "T Stop"))
        self.TDAFLabel5.setText(_translate("MainWindow", "DC Stop"))
        self.TDAFLabel8.setText(_translate("MainWindow", "AC Stop"))
        self.TDAFLabel11.setText(_translate("MainWindow", "F Stop"))
        self.TDAFLabel13.setText(_translate("MainWindow", "T current"))
        self.TDAFLabel3.setText(_translate("MainWindow", "T Step"))
        self.TDAFLabel6.setText(_translate("MainWindow", "DC Step"))
        self.TDAFLabel9.setText(_translate("MainWindow", "AC Step"))
        self.TDAFLabel12.setText(_translate("MainWindow", "SampleCount"))
        self.tempStartValue.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>T Start</p></body></html>"))
        self.menuZurich_Instruments_Control_Panel.setTitle(_translate("MainWindow", "PyZurich"))
        self.actionAbout_PyZurich.setText(_translate("MainWindow", "About PyZurich"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
