# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VinSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AdvancedSettings_Vin = QtWidgets.QLabel(self.centralwidget)
        self.AdvancedSettings_Vin.setGeometry(QtCore.QRect(217, 20, 165, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AdvancedSettings_Vin.setFont(font)
        self.AdvancedSettings_Vin.setObjectName("AdvancedSettings_Vin")
        self.VoltageInput = QtWidgets.QLabel(self.centralwidget)
        self.VoltageInput.setGeometry(QtCore.QRect(254, 40, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VoltageInput.setFont(font)
        self.VoltageInput.setObjectName("VoltageInput")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(110, 80, 371, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.VoltageInGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.VoltageInGrid.setContentsMargins(0, 0, 0, 0)
        self.VoltageInGrid.setObjectName("VoltageInGrid")
        self.VoltageInLabel4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel4.setObjectName("VoltageInLabel4")
        self.VoltageInGrid.addWidget(self.VoltageInLabel4, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VoltageInLabel3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel3.setObjectName("VoltageInLabel3")
        self.VoltageInGrid.addWidget(self.VoltageInLabel3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VoltageInLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel2.setObjectName("VoltageInLabel2")
        self.VoltageInGrid.addWidget(self.VoltageInLabel2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.DIff = QtWidgets.QHBoxLayout()
        self.DIff.setObjectName("DIff")
        self.diffYes = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.diffYes.setObjectName("diffYes")
        self.DIff.addWidget(self.diffYes)
        self.diffNo = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.diffNo.setObjectName("diffNo")
        self.DIff.addWidget(self.diffNo)
        self.VoltageInGrid.addLayout(self.DIff, 2, 1, 1, 1)
        self.VoltageInLabel1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel1.setObjectName("VoltageInLabel1")
        self.VoltageInGrid.addWidget(self.VoltageInLabel1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Imp50 = QtWidgets.QHBoxLayout()
        self.Imp50.setObjectName("Imp50")
        self.imp50Yes = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.imp50Yes.setObjectName("imp50Yes")
        self.Imp50.addWidget(self.imp50Yes)
        self.imp50No = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.imp50No.setObjectName("imp50No")
        self.Imp50.addWidget(self.imp50No)
        self.VoltageInGrid.addLayout(self.Imp50, 1, 1, 1, 1)
        self.ACCoupling_2 = QtWidgets.QHBoxLayout()
        self.ACCoupling_2.setObjectName("ACCoupling_2")
        self.acCouplingYes_ZI = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.acCouplingYes_ZI.setObjectName("acCouplingYes_ZI")
        self.ACCoupling_2.addWidget(self.acCouplingYes_ZI)
        self.acCouplingNo_ZI = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.acCouplingNo_ZI.setObjectName("acCouplingNo_ZI")
        self.ACCoupling_2.addWidget(self.acCouplingNo_ZI)
        self.VoltageInGrid.addLayout(self.ACCoupling_2, 3, 1, 1, 1)
        self.voltageInRange = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.voltageInRange.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageInRange.setObjectName("voltageInRange")
        self.VoltageInGrid.addWidget(self.voltageInRange, 0, 1, 1, 1)
        self.pageUp = QtWidgets.QPushButton(self.centralwidget)
        self.pageUp.setGeometry(QtCore.QRect(20, 10, 61, 32))
        self.pageUp.setObjectName("pageUp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AdvancedSettings_Vin.setText(_translate("MainWindow", "Advanced Settings"))
        self.VoltageInput.setText(_translate("MainWindow", "Voltage Input"))
        self.VoltageInLabel4.setText(_translate("MainWindow", "AC Coupling"))
        self.VoltageInLabel3.setText(_translate("MainWindow", "Differentiate"))
        self.VoltageInLabel2.setText(_translate("MainWindow", "Imp 50"))
        self.diffYes.setText(_translate("MainWindow", "Yes"))
        self.diffNo.setText(_translate("MainWindow", "No"))
        self.VoltageInLabel1.setText(_translate("MainWindow", "Range"))
        self.imp50Yes.setText(_translate("MainWindow", "Yes"))
        self.imp50No.setText(_translate("MainWindow", "No"))
        self.acCouplingYes_ZI.setText(_translate("MainWindow", "Yes"))
        self.acCouplingNo_ZI.setText(_translate("MainWindow", "No"))
        self.pageUp.setText(_translate("MainWindow", "＜--"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
