# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AdvancedSettings_Vin = QtWidgets.QLabel(self.centralwidget)
        self.AdvancedSettings_Vin.setGeometry(QtCore.QRect(150, 20, 300, 50))
        self.AdvancedSettings_Vin.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AdvancedSettings_Vin.setFont(font)
        self.AdvancedSettings_Vin.setAlignment(QtCore.Qt.AlignCenter)
        self.AdvancedSettings_Vin.setObjectName("AdvancedSettings_Vin")
        self.VoltageInput = QtWidgets.QLabel(self.centralwidget)
        self.VoltageInput.setGeometry(QtCore.QRect(200, 50, 200, 50))
        self.VoltageInput.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VoltageInput.setFont(font)
        self.VoltageInput.setAlignment(QtCore.Qt.AlignCenter)
        self.VoltageInput.setObjectName("VoltageInput")
        self.pageUp = QtWidgets.QPushButton(self.centralwidget)
        self.pageUp.setGeometry(QtCore.QRect(20, 10, 61, 32))
        self.pageUp.setObjectName("pageUp")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(110, 100, 371, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.VoltageInGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.VoltageInGrid.setContentsMargins(0, 0, 0, 0)
        self.VoltageInGrid.setObjectName("VoltageInGrid")
        self.VoltageInLabel1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel1.setMinimumSize(QtCore.QSize(100, 0))
        self.VoltageInLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.VoltageInLabel1.setObjectName("VoltageInLabel1")
        self.VoltageInGrid.addWidget(self.VoltageInLabel1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VoltageInLabel3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel3.setMinimumSize(QtCore.QSize(100, 0))
        self.VoltageInLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.VoltageInLabel3.setObjectName("VoltageInLabel3")
        self.VoltageInGrid.addWidget(self.VoltageInLabel3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.voltageInRange_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.voltageInRange_1.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageInRange_1.setObjectName("voltageInRange_1")
        self.VoltageInGrid.addWidget(self.voltageInRange_1, 0, 1, 1, 1)
        self.VoltageInLabel4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel4.setMinimumSize(QtCore.QSize(100, 0))
        self.VoltageInLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.VoltageInLabel4.setObjectName("VoltageInLabel4")
        self.VoltageInGrid.addWidget(self.VoltageInLabel4, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VoltageInLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel2.setMinimumSize(QtCore.QSize(100, 0))
        self.VoltageInLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.VoltageInLabel2.setObjectName("VoltageInLabel2")
        self.VoltageInGrid.addWidget(self.VoltageInLabel2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox.setObjectName("groupBox")
        self.Imp50 = QtWidgets.QHBoxLayout(self.groupBox)
        self.Imp50.setObjectName("Imp50")
        self.imp50Yes = QtWidgets.QRadioButton(self.groupBox)
        self.imp50Yes.setObjectName("imp50Yes")
        self.Imp50.addWidget(self.imp50Yes, 0, QtCore.Qt.AlignHCenter)
        self.imp50No = QtWidgets.QRadioButton(self.groupBox)
        self.imp50No.setObjectName("imp50No")
        self.Imp50.addWidget(self.imp50No, 0, QtCore.Qt.AlignHCenter)
        self.VoltageInGrid.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox1.setObjectName("groupBox1")
        self.DIff = QtWidgets.QHBoxLayout(self.groupBox1)
        self.DIff.setObjectName("DIff")
        self.diffYes = QtWidgets.QRadioButton(self.groupBox1)
        self.diffYes.setObjectName("diffYes")
        self.DIff.addWidget(self.diffYes, 0, QtCore.Qt.AlignHCenter)
        self.diffNo = QtWidgets.QRadioButton(self.groupBox1)
        self.diffNo.setObjectName("diffNo")
        self.DIff.addWidget(self.diffNo, 0, QtCore.Qt.AlignHCenter)
        self.VoltageInGrid.addWidget(self.groupBox1, 2, 1, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox2.setObjectName("groupBox2")
        self.ACCoupling_1 = QtWidgets.QHBoxLayout(self.groupBox2)
        self.ACCoupling_1.setObjectName("ACCoupling_1")
        self.acCouplingYes_ZI = QtWidgets.QRadioButton(self.groupBox2)
        self.acCouplingYes_ZI.setObjectName("acCouplingYes_ZI")
        self.ACCoupling_1.addWidget(self.acCouplingYes_ZI, 0, QtCore.Qt.AlignHCenter)
        self.acCouplingNo_ZI = QtWidgets.QRadioButton(self.groupBox2)
        self.acCouplingNo_ZI.setObjectName("acCouplingNo_ZI")
        self.ACCoupling_1.addWidget(self.acCouplingNo_ZI, 0, QtCore.Qt.AlignHCenter)
        self.VoltageInGrid.addWidget(self.groupBox2, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AdvancedSettings_Vin.setText(_translate("MainWindow", "Advanced Settings"))
        self.VoltageInput.setText(_translate("MainWindow", "Voltage Input"))
        self.pageUp.setText(_translate("MainWindow", "＜--"))
        self.VoltageInLabel1.setText(_translate("MainWindow", "Input Range (V)"))
        self.VoltageInLabel3.setText(_translate("MainWindow", "Differentiate"))
        self.VoltageInLabel4.setText(_translate("MainWindow", "AC Coupling"))
        self.VoltageInLabel2.setText(_translate("MainWindow", "Imp 50"))
        self.imp50Yes.setText(_translate("MainWindow", "Yes"))
        self.imp50No.setText(_translate("MainWindow", "No"))
        self.diffYes.setText(_translate("MainWindow", "Yes"))
        self.diffNo.setText(_translate("MainWindow", "No"))
        self.acCouplingYes_ZI.setText(_translate("MainWindow", "Yes"))
        self.acCouplingNo_ZI.setText(_translate("MainWindow", "No"))
