# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AdvancedSettings_Vin = QtWidgets.QLabel(self.centralwidget)
        self.AdvancedSettings_Vin.setGeometry(QtCore.QRect(217, 20, 165, 24))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AdvancedSettings_Vin.setFont(font)
        self.AdvancedSettings_Vin.setObjectName("AdvancedSettings_Vin")
        self.VoltageInput = QtWidgets.QLabel(self.centralwidget)
        self.VoltageInput.setGeometry(QtCore.QRect(254, 40, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VoltageInput.setFont(font)
        self.VoltageInput.setObjectName("VoltageInput")
        self.pageUp = QtWidgets.QPushButton(self.centralwidget)
        self.pageUp.setGeometry(QtCore.QRect(20, 10, 61, 32))
        self.pageUp.setObjectName("pageUp")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 70, 471, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.Channel1 = QtWidgets.QWidget()
        self.Channel1.setObjectName("Channel1")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Channel1)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(50, 10, 371, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.VoltageInGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.VoltageInGrid.setContentsMargins(0, 0, 0, 0)
        self.VoltageInGrid.setObjectName("VoltageInGrid")
        self.ACCoupling_1 = QtWidgets.QHBoxLayout()
        self.ACCoupling_1.setObjectName("ACCoupling_1")
        self.acCouplingYes_ZI_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.acCouplingYes_ZI_1.setObjectName("acCouplingYes_ZI_1")
        self.ACCoupling_1.addWidget(self.acCouplingYes_ZI_1)
        self.acCouplingNo_ZI_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.acCouplingNo_ZI_1.setObjectName("acCouplingNo_ZI_1")
        self.ACCoupling_1.addWidget(self.acCouplingNo_ZI_1)
        self.VoltageInGrid.addLayout(self.ACCoupling_1, 3, 1, 1, 1)
        self.DIff = QtWidgets.QHBoxLayout()
        self.DIff.setObjectName("DIff")
        self.diffYes_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.diffYes_1.setObjectName("diffYes_1")
        self.DIff.addWidget(self.diffYes_1)
        self.diffNo_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.diffNo_1.setObjectName("diffNo_1")
        self.DIff.addWidget(self.diffNo_1)
        self.VoltageInGrid.addLayout(self.DIff, 2, 1, 1, 1)
        self.VoltageInLabel1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel1.setObjectName("VoltageInLabel1")
        self.VoltageInGrid.addWidget(self.VoltageInLabel1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VoltageInLabel3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel3.setObjectName("VoltageInLabel3")
        self.VoltageInGrid.addWidget(self.VoltageInLabel3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.voltageInRange_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.voltageInRange_1.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageInRange_1.setObjectName("voltageInRange_1")
        self.VoltageInGrid.addWidget(self.voltageInRange_1, 0, 1, 1, 1)
        self.VoltageInLabel4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel4.setObjectName("VoltageInLabel4")
        self.VoltageInGrid.addWidget(self.VoltageInLabel4, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Imp50 = QtWidgets.QHBoxLayout()
        self.Imp50.setObjectName("Imp50")
        self.imp50Yes_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.imp50Yes_1.setObjectName("imp50Yes_1")
        self.Imp50.addWidget(self.imp50Yes_1)
        self.imp50No_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.imp50No_1.setObjectName("imp50No_1")
        self.Imp50.addWidget(self.imp50No_1)
        self.VoltageInGrid.addLayout(self.Imp50, 1, 1, 1, 1)
        self.VoltageInLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.VoltageInLabel2.setObjectName("VoltageInLabel2")
        self.VoltageInGrid.addWidget(self.VoltageInLabel2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tabWidget.addTab(self.Channel1, "")
        self.Channel2 = QtWidgets.QWidget()
        self.Channel2.setObjectName("Channel2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Channel2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(50, 10, 371, 231))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.VoltageInGrid_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.VoltageInGrid_2.setContentsMargins(0, 0, 0, 0)
        self.VoltageInGrid_2.setObjectName("VoltageInGrid_2")
        self.DIff_2 = QtWidgets.QHBoxLayout()
        self.DIff_2.setObjectName("DIff_2")
        self.diffYes_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.diffYes_2.setObjectName("diffYes_2")
        self.DIff_2.addWidget(self.diffYes_2)
        self.diffNo_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.diffNo_2.setObjectName("diffNo_2")
        self.DIff_2.addWidget(self.diffNo_2)
        self.VoltageInGrid_2.addLayout(self.DIff_2, 2, 1, 1, 1)
        self.VoltageInLabel1_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VoltageInLabel1_2.setObjectName("VoltageInLabel1_2")
        self.VoltageInGrid_2.addWidget(self.VoltageInLabel1_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Imp50_2 = QtWidgets.QHBoxLayout()
        self.Imp50_2.setObjectName("Imp50_2")
        self.imp50Yes_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.imp50Yes_2.setObjectName("imp50Yes_2")
        self.Imp50_2.addWidget(self.imp50Yes_2)
        self.imp50No_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.imp50No_2.setObjectName("imp50No_2")
        self.Imp50_2.addWidget(self.imp50No_2)
        self.VoltageInGrid_2.addLayout(self.Imp50_2, 1, 1, 1, 1)
        self.VoltageInLabel4_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VoltageInLabel4_2.setObjectName("VoltageInLabel4_2")
        self.VoltageInGrid_2.addWidget(self.VoltageInLabel4_2, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.VoltageInLabel2_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VoltageInLabel2_2.setObjectName("VoltageInLabel2_2")
        self.VoltageInGrid_2.addWidget(self.VoltageInLabel2_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.voltageInRange_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.voltageInRange_2.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageInRange_2.setObjectName("voltageInRange_2")
        self.VoltageInGrid_2.addWidget(self.voltageInRange_2, 0, 1, 1, 1)
        self.VoltageInLabel3_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.VoltageInLabel3_2.setObjectName("VoltageInLabel3_2")
        self.VoltageInGrid_2.addWidget(self.VoltageInLabel3_2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ACCoupling_2 = QtWidgets.QHBoxLayout()
        self.ACCoupling_2.setObjectName("ACCoupling_2")
        self.acCouplingYes_ZI_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.acCouplingYes_ZI_2.setObjectName("acCouplingYes_ZI_2")
        self.ACCoupling_2.addWidget(self.acCouplingYes_ZI_2)
        self.acCouplingNo_ZI_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.acCouplingNo_ZI_2.setObjectName("acCouplingNo_ZI_2")
        self.ACCoupling_2.addWidget(self.acCouplingNo_ZI_2)
        self.VoltageInGrid_2.addLayout(self.ACCoupling_2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.Channel2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AdvancedSettings_Vin.setText(_translate("MainWindow", "Advanced Settings"))
        self.VoltageInput.setText(_translate("MainWindow", "Voltage Input"))
        self.pageUp.setText(_translate("MainWindow", "＜--"))
        self.acCouplingYes_ZI_1.setText(_translate("MainWindow", "Yes"))
        self.acCouplingNo_ZI_1.setText(_translate("MainWindow", "No"))
        self.diffYes_1.setText(_translate("MainWindow", "Yes"))
        self.diffNo_1.setText(_translate("MainWindow", "No"))
        self.VoltageInLabel1.setText(_translate("MainWindow", "Range"))
        self.VoltageInLabel3.setText(_translate("MainWindow", "Differentiate"))
        self.VoltageInLabel4.setText(_translate("MainWindow", "AC Coupling"))
        self.imp50Yes_1.setText(_translate("MainWindow", "Yes"))
        self.imp50No_1.setText(_translate("MainWindow", "No"))
        self.VoltageInLabel2.setText(_translate("MainWindow", "Imp 50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Channel1), _translate("MainWindow", "Channel1"))
        self.diffYes_2.setText(_translate("MainWindow", "Yes"))
        self.diffNo_2.setText(_translate("MainWindow", "No"))
        self.VoltageInLabel1_2.setText(_translate("MainWindow", "Range"))
        self.imp50Yes_2.setText(_translate("MainWindow", "Yes"))
        self.imp50No_2.setText(_translate("MainWindow", "No"))
        self.VoltageInLabel4_2.setText(_translate("MainWindow", "AC Coupling"))
        self.VoltageInLabel2_2.setText(_translate("MainWindow", "Imp 50"))
        self.VoltageInLabel3_2.setText(_translate("MainWindow", "Differentiate"))
        self.acCouplingYes_ZI_2.setText(_translate("MainWindow", "Yes"))
        self.acCouplingNo_ZI_2.setText(_translate("MainWindow", "No"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Channel2), _translate("MainWindow", "Channel2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
